Console.Write("Введите коррдинаты x для первой точки ");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите коррдинаты y для первой точки ");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите коррдинаты z для первой точки ");
int z1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите коррдинаты x для второй точки ");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите коррдинаты y для второй точки ");
int y2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите коррдинаты z для второй точки ");
int z2 = Convert.ToInt32(Console.ReadLine());
double s = Math.Sqrt(Math.Pow(x2-x1,2)+Math.Pow(y2-y1,2)+Math.Pow(z2-z1,2));
Console.WriteLine(Math.Round(s,2));